name: Flutter PGO Build

on:
  push:
    branches:
      - workflow

jobs:
  profile-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Profile Mode)
        run:  flutter build apk --profile --target-platform android-arm64


      - name: Upload Profile Data
        uses: actions/upload-artifact@v3
        with:
          name: profile-data
          path: build/app/profile_data.json

  optimize-build:
    needs: profile-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Download Profile Data
        uses: actions/download-artifact@v3
        with:
          name: profile-data

      - name: Build Optimized Release
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk